// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: assistant.proto

package assistantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TranscribeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *TranscribeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type TranscribeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Text             string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence       float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DetectedLanguage string                 `protobuf:"bytes,3,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscribeResponse) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type PartialTranscript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialTranscript) Reset() {
	*x = PartialTranscript{}
	mi := &file_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialTranscript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialTranscript) ProtoMessage() {}

func (x *PartialTranscript) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialTranscript.ProtoReflect.Descriptor instead.
func (*PartialTranscript) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *PartialTranscript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PartialTranscript) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

type SynthesizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_assistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{5}
}

func (x *SynthesizeResponse) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SynthesizeResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SynthesizeResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_assistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	LoadedModels  []string               `protobuf:"bytes,3,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_assistant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetLoadedModels() []string {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

var File_assistant_proto protoreflect.FileDescriptor

const file_assistant_proto_rawDesc = "" +
	"\n" +
	"\x0fassistant.proto\x12\fassistant.v1\"f\n" +
	"\x11TranscribeRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"u\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x11detected_language\x18\x03 \x01(\tR\x10detectedLanguage\"A\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"B\n" +
	"\x11PartialTranscript\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"=\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\"c\n" +
	"\x12SynthesizeResponse\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\x0f\n" +
	"\rHealthRequest\"_\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rloaded_models\x18\x03 \x03(\tR\floadedModels2\xca\x02\n" +
	"\tMLService\x12O\n" +
	"\n" +
	"Transcribe\x12\x1f.assistant.v1.TranscribeRequest\x1a .assistant.v1.TranscribeResponse\x12Q\n" +
	"\x10StreamTranscribe\x12\x18.assistant.v1.AudioChunk\x1a\x1f.assistant.v1.PartialTranscript(\x010\x01\x12O\n" +
	"\n" +
	"Synthesize\x12\x1f.assistant.v1.SynthesizeRequest\x1a .assistant.v1.SynthesizeResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.assistant.v1.HealthRequest\x1a\x1c.assistant.v1.HealthResponseBCZAgithub.com/you/voice-assistant/internal/sidecar/proto;assistantpbb\x06proto3"

var (
	file_assistant_proto_rawDescOnce sync.Once
	file_assistant_proto_rawDescData []byte
)

func file_assistant_proto_rawDescGZIP() []byte {
	file_assistant_proto_rawDescOnce.Do(func() {
		file_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)))
	})
	return file_assistant_proto_rawDescData
}

var file_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_assistant_proto_goTypes = []any{
	(*TranscribeRequest)(nil),  // 0: assistant.v1.TranscribeRequest
	(*TranscribeResponse)(nil), // 1: assistant.v1.TranscribeResponse
	(*AudioChunk)(nil),         // 2: assistant.v1.AudioChunk
	(*PartialTranscript)(nil),  // 3: assistant.v1.PartialTranscript
	(*SynthesizeRequest)(nil),  // 4: assistant.v1.SynthesizeRequest
	(*SynthesizeResponse)(nil), // 5: assistant.v1.SynthesizeResponse
	(*HealthRequest)(nil),      // 6: assistant.v1.HealthRequest
	(*HealthResponse)(nil),     // 7: assistant.v1.HealthResponse
}
var file_assistant_proto_depIdxs = []int32{
	0, // 0: assistant.v1.MLService.Transcribe:input_type -> assistant.v1.TranscribeRequest
	2, // 1: assistant.v1.MLService.StreamTranscribe:input_type -> assistant.v1.AudioChunk
	4, // 2: assistant.v1.MLService.Synthesize:input_type -> assistant.v1.SynthesizeRequest
	6, // 3: assistant.v1.MLService.HealthCheck:input_type -> assistant.v1.HealthRequest
	1, // 4: assistant.v1.MLService.Transcribe:output_type -> assistant.v1.TranscribeResponse
	3, // 5: assistant.v1.MLService.StreamTranscribe:output_type -> assistant.v1.PartialTranscript
	5, // 6: assistant.v1.MLService.Synthesize:output_type -> assistant.v1.SynthesizeResponse
	7, // 7: assistant.v1.MLService.HealthCheck:output_type -> assistant.v1.HealthResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assistant_proto_init() }
func file_assistant_proto_init() {
	if File_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assistant_proto_goTypes,
		DependencyIndexes: file_assistant_proto_depIdxs,
		MessageInfos:      file_assistant_proto_msgTypes,
	}.Build()
	File_assistant_proto = out.File
	file_assistant_proto_goTypes = nil
	file_assistant_proto_depIdxs = nil
}
