# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/assistant.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/assistant.proto\x12\x0c\x61ssistant.v1\"I\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08language\x18\x03 \x01(\t\"Q\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x19\n\x11\x64\x65tected_language\x18\x03 \x01(\t\"/\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"3\n\x11PartialTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\"0\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\"H\n\x12SynthesizeResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x15\n\rloaded_models\x18\x03 \x03(\t2\xca\x02\n\tMLService\x12O\n\nTranscribe\x12\x1f.assistant.v1.TranscribeRequest\x1a .assistant.v1.TranscribeResponse\x12Q\n\x10StreamTranscribe\x12\x18.assistant.v1.AudioChunk\x1a\x1f.assistant.v1.PartialTranscript(\x01\x30\x01\x12O\n\nSynthesize\x12\x1f.assistant.v1.SynthesizeRequest\x1a .assistant.v1.SynthesizeResponse\x12H\n\x0bHealthCheck\x12\x1b.assistant.v1.HealthRequest\x1a\x1c.assistant.v1.HealthResponseBCZAgithub.com/you/voice-assistant/internal/sidecar/proto;assistantpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/you/voice-assistant/internal/sidecar/proto;assistantpb'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=39
  _globals['_TRANSCRIBEREQUEST']._serialized_end=112
  _globals['_TRANSCRIBERESPONSE']._serialized_start=114
  _globals['_TRANSCRIBERESPONSE']._serialized_end=195
  _globals['_AUDIOCHUNK']._serialized_start=197
  _globals['_AUDIOCHUNK']._serialized_end=244
  _globals['_PARTIALTRANSCRIPT']._serialized_start=246
  _globals['_PARTIALTRANSCRIPT']._serialized_end=297
  _globals['_SYNTHESIZEREQUEST']._serialized_start=299
  _globals['_SYNTHESIZEREQUEST']._serialized_end=347
  _globals['_SYNTHESIZERESPONSE']._serialized_start=349
  _globals['_SYNTHESIZERESPONSE']._serialized_end=421
  _globals['_HEALTHREQUEST']._serialized_start=423
  _globals['_HEALTHREQUEST']._serialized_end=438
  _globals['_HEALTHRESPONSE']._serialized_start=440
  _globals['_HEALTHRESPONSE']._serialized_end=508
  _globals['_MLSERVICE']._serialized_start=511
  _globals['_MLSERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
