# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import assistant_pb2 as proto_dot_assistant__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/assistant.v1.MLService/Transcribe',
                request_serializer=proto_dot_assistant__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=proto_dot_assistant__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.StreamTranscribe = channel.stream_stream(
                '/assistant.v1.MLService/StreamTranscribe',
                request_serializer=proto_dot_assistant__pb2.AudioChunk.SerializeToString,
                response_deserializer=proto_dot_assistant__pb2.PartialTranscript.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/assistant.v1.MLService/Synthesize',
                request_serializer=proto_dot_assistant__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=proto_dot_assistant__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/assistant.v1.MLService/HealthCheck',
                request_serializer=proto_dot_assistant__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_assistant__pb2.HealthResponse.FromString,
                _registered_method=True)


class MLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=proto_dot_assistant__pb2.TranscribeRequest.FromString,
                    response_serializer=proto_dot_assistant__pb2.TranscribeResponse.SerializeToString,
            ),
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=proto_dot_assistant__pb2.AudioChunk.FromString,
                    response_serializer=proto_dot_assistant__pb2.PartialTranscript.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=proto_dot_assistant__pb2.SynthesizeRequest.FromString,
                    response_serializer=proto_dot_assistant__pb2.SynthesizeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_assistant__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_assistant__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assistant.v1.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assistant.v1.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.v1.MLService/Transcribe',
            proto_dot_assistant__pb2.TranscribeRequest.SerializeToString,
            proto_dot_assistant__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/assistant.v1.MLService/StreamTranscribe',
            proto_dot_assistant__pb2.AudioChunk.SerializeToString,
            proto_dot_assistant__pb2.PartialTranscript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.v1.MLService/Synthesize',
            proto_dot_assistant__pb2.SynthesizeRequest.SerializeToString,
            proto_dot_assistant__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.v1.MLService/HealthCheck',
            proto_dot_assistant__pb2.HealthRequest.SerializeToString,
            proto_dot_assistant__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
